### ISSUE TITLE
Hello,do you have the processed Texas dataset used in your paper？ 

### ISSUE THREAD

**Issue by czq1503** [inspire-group/membership-inference-evaluation#1]
This file seems missing in your github repo，thanks！

**Comment by lwsong** [comment]
For adversarial regularization, the dataset download and data processing are already defined in the utility function: https://github.com/inspire-group/membership-inference-evaluation/blob/master/adversarial%20regularization/utils.py  
For MemGuard, we also provide a link to download the processed Texas dataset in the README file: https://github.com/inspire-group/membership-inference-evaluation/blob/master/MemGuard/README.md
